# Generated by Django 4.2.7 on 2023-11-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcendance_backend", "0004_alter_player_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="games",
            field=models.ManyToManyField(blank=True, to="transcendance_backend.game"),
        ),
        migrations.AlterField(
            model_name="player",
            name="tournaments",
            field=models.ManyToManyField(
                blank=True, to="transcendance_backend.tournament"
            ),
        ),
    ]
