# Generated by Django 4.2.7 on 2023-11-10 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcendance_backend", "0007_alter_tournament_joined_players"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="joined_players",
            new_name="players",
        ),
    ]
