# Generated by Django 4.2.7 on 2023-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendance_backend', '0009_alter_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games_played', through='transcendance_backend.GameStat', to='transcendance_backend.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, to='transcendance_backend.player'),
        ),
    ]
