# Generated by Django 4.2.7 on 2024-01-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcendance_backend",
            "0011_remove_tournament_pools_game_power_ups_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transcendance_backend.player",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="username",
            field=models.CharField(default="Guest", max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
