# Generated by Django 4.2.7 on 2024-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcendance_backend",
            "0012_game_created_by_player_username_alter_player_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
