# Generated by Django 4.2.7 on 2024-02-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcendance_backend", "0013_alter_player_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="id_42",
            field=models.IntegerField(null=True),
        ),
    ]
