# Generated by Django 4.2.7 on 2024-02-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transcendance_backend", "0021_player_games"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="games",
        ),
        migrations.AddField(
            model_name="game",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transcendance_backend.tournament",
            ),
        ),
    ]
