# Generated by Django 4.2.10 on 2024-02-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transcendance_backend", "0022_remove_tournament_games_game_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="p1_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="p2_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournaments_won",
                to="transcendance_backend.player",
            ),
        ),
    ]
