# Generated by Django 4.2.10 on 2024-02-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcendance_backend",
            "0025_game_paddle_hits_game_wall_hits_player_lastgameid",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="ready_players",
            field=models.ManyToManyField(
                blank=True,
                related_name="tournament_ready_players",
                to="transcendance_backend.player",
            ),
        ),
    ]
