# Generated by Django 4.2.7 on 2023-11-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_players",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2, "2 Players"),
                            (4, "4 Players"),
                            (6, "6 Players"),
                            (8, "8 Players"),
                        ]
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("simple", "Simple"), ("evil", "Evil")], max_length=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("games_played", models.PositiveIntegerField(default=0)),
                (
                    "blocked_players",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocked_by",
                        to="transcendance_backend.player",
                    ),
                ),
                (
                    "games_list",
                    models.ManyToManyField(
                        related_name="players", to="transcendance_backend.game"
                    ),
                ),
            ],
        ),
    ]
