global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'webhook'

receivers:
- name: 'webhook'
  webhook_configs:
  - url: '${TO_REPLACE}'
    send_resolved: true
    http_config:
      tls_config:
        insecure_skip_verify: true
