version: "3.8"

services:
  backend:
    container_name: backend
    build: ./backend
    image: backend
    ports:
      - "5432:5432"
    volumes:
      - backend:/volumes/backend
    networks:
      - ft_transcendence
    env_file:
      - .env
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    ports:
      - "8000:443"
    volumes:
      - backend:/volumes/backend
    networks:
      - ft_transcendence
    env_file:
      - .env
    restart: on-failure

  prometheus:
    container_name: prometheus
    build: ./prometheus
    image: prometheus
    volumes:
      - prometheus:/etc/prometheus
    ports:
      - '9090:9090'
    networks:
      - ft_transcendence
    env_file:
      - .env
    restart: unless-stopped
  alertmanager:
    container_name: alertmanager
    build: ./alertmanager
    image: alertmanager
    volumes:
      - alertmanager:/etc/alertmanager
    ports:
      - '9093:9093'
    networks:
      - ft_transcendence
    env_file:
      - .env
    restart: unless-stopped
  grafana:
    container_name: grafana
    build: ./grafana
    image: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/etc/grafana/provisioning/datasources
    networks:
      - ft_transcendence
    env_file:
      - .env
    restart: unless-stopped

volumes:
  backend:
    name: backend
    driver: local
    driver_opts:
      device: /sgoinfre/goinfre/Perso/rsterin/data/backend
      o: bind
      type: none
  prometheus:
    name: prometheus
    driver: local
    driver_opts:
      device: /sgoinfre/goinfre/Perso/rsterin/data/prometheus
      o: bind
      type: none
  grafana:
    name: grafana
    driver: local
    driver_opts:
      device: /sgoinfre/goinfre/Perso/rsterin/data/grafana
      o: bind
      type: none
  alertmanager:
    name: alertmanager
    driver: local
    driver_opts:
      device: /sgoinfre/goinfre/Perso/rsterin/data/alertmanager
      o: bind
      type: none

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge
