# Generated by Django 4.2.7 on 2023-11-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcendence_backend", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
        migrations.RemoveField(
            model_name="player",
            name="blocked_players",
        ),
        migrations.RemoveField(
            model_name="player",
            name="games_list",
        ),
        migrations.RemoveField(
            model_name="player",
            name="games_played",
        ),
        migrations.AddField(
            model_name="player",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="player",
            name="xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
