# Generated by Django 4.2.7 on 2023-11-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcendence_backend",
            "0003_pool_remove_game_difficulty_remove_game_num_players_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
