# Generated by Django 4.2.7 on 2023-11-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcendence_backend", "0005_alter_player_games_alter_player_tournaments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="pools",
            field=models.ManyToManyField(
                blank=True, related_name="tournaments", to="transcendence_backend.pool"
            ),
        ),
    ]
