# Generated by Django 4.2.7 on 2023-11-10 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcendence_backend", "0008_rename_joined_players_tournament_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                related_name="games_played",
                through="transcendence_backend.GameStat",
                to="transcendence_backend.player",
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=1, message="At least one player is required."
                    )
                ],
            ),
        ),
    ]
