# Generated by Django 4.2.7 on 2024-01-24 14:34

from django.db import migrations, models
import transcendence_backend.validators


class Migration(migrations.Migration):
    dependencies = [
        ("transcendence_backend", "0010_alter_game_players_alter_player_blocked_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="pools",
        ),
        migrations.AddField(
            model_name="game",
            name="power_ups",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="games",
            field=models.ManyToManyField(blank=True, to="transcendence_backend.game"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="power_ups",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="state",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("running", "Running"),
                    ("done", "Done"),
                ],
                default="waiting",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="required_player_number",
            field=models.PositiveIntegerField(
                default=4,
                validators=[transcendence_backend.validators.even_value_validator],
            ),
        ),
        migrations.DeleteModel(
            name="Pool",
        ),
    ]
