# Generated by Django 4.2.7 on 2024-01-31 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "transcendence_backend",
            "0011_remove_tournament_pools_game_power_ups_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="avatar",
            field=models.ImageField(
                default="avatar/default.jpg", null=True, upload_to="avatars"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
