# Generated by Django 4.2.7 on 2024-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcendence_backend", "0012_player_avatar_player_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.jpg", null=True, upload_to="avatars"
            ),
        ),
    ]
