# Generated by Django 4.2.7 on 2024-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcendence_backend", "0014_player_id_42"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="url_profile_42",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
