# Generated by Django 4.2.7 on 2024-02-02 17:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcendence_backend",
            "0016_player_friend_users_player_is_connected_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="required_player_number",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="required_player_number",
        ),
        migrations.AddField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="game",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transcendence_backend.player",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="state",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("round 1", "ROUND 1"),
                    ("round 2", "ROUND 2"),
                    ("done", "Done"),
                ],
                default="waiting",
                max_length=10,
            ),
        ),
    ]
