# Generated by Django 4.2.7 on 2024-02-05 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcendence_backend", "0017_remove_game_required_player_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="name",
            new_name="nickname",
        ),
    ]
