# Generated by Django 4.2.7 on 2024-02-05 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcendence_backend", "0018_rename_name_player_nickname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="games",
        ),
    ]
