# Generated by Django 4.2.7 on 2024-02-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcendence_backend",
            "0020_tournament_goal_objective_alter_tournament_games",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="games",
            field=models.ManyToManyField(
                related_name="games_played",
                through="transcendence_backend.GameStat",
                to="transcendence_backend.game",
            ),
        ),
    ]
