groups:
  - name: HighCPU
    rules:
      - alert: HighCPUUsage
        expr: node_cpu_seconds_total / node_uptime_seconds > 0.05
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage on {{$labels.instance}}"
          description: "CPU usage is above 80% for more than 5 minutes."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal - node_memory_MemFree - node_memory_Buffers - node_memory_Cached) / node_memory_MemTotal * 100 > 90
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High Memory usage detected"
          description: "Memory usage is above 90% for the last 10 minutes."
